# Generated by Django 5.2.5 on 2025-09-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('termas', '0003_ciudad_region_alter_terma_ciudad_ciudad_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
