# Generated by Django 5.2.5 on 2025-10-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0010_solicitudterma_rut_empresa'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='terma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='termas.terma'),
        ),
    ]
