# Generated by Django 5.2.5 on 2025-10-16 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_compra_terma'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_visita',
            field=models.DateField(default=datetime.date.today, help_text='Fecha para la que es válida la entrada'),
        ),
    ]
