# Generated by Django 5.2.5 on 2025-10-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0011_servicioterma_descripcion_servicioterma_precio'),
        ('ventas', '0003_compra_fecha_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='detalles_compra', to='termas.servicioterma'),
        ),
    ]
