# Generated by Django 5.2.5 on 2025-10-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detallecompra_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_confirmacion_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='pagador_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
