# Generated by Django 5.2.5 on 2025-10-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_compra_fecha_confirmacion_pago_compra_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment ID de Mercado Pago', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='mercado_pago_id',
            field=models.CharField(blank=True, help_text='Preference ID de Mercado Pago', max_length=100, null=True),
        ),
    ]
