# Generated by Django 5.2.5 on 2025-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_compra_payment_id_alter_compra_mercado_pago_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='compra',
            name='mercado_pago_id',
            field=models.CharField(blank=True, help_text='ID de la preferencia de Mercado Pago', max_length=100, null=True),
        ),
    ]
