# Generated by Django 5.2.5 on 2025-10-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_compra_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment ID de Mercado Pago', max_length=100, null=True),
        ),
    ]
