# Generated by Django 5.2.5 on 2025-11-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tokenrestablecercontrasena'),
        ('ventas', '0009_compra_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEscaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255)),
                ('codigo_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.codigoqr')),
                ('usuario_scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
    ]
