# Generated by Django 5.2.5 on 2025-11-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_create_missing_qr_codes'),
        ('ventas', '0010_registroescaneo'),
    ]

    operations = [
    ]
