# Generated by Django 5.2.5 on 2025-11-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_merge_20251105_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
