# Generated by Django 5.2.5 on 2025-11-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_detallecompra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='visible',
            field=models.BooleanField(default=True, help_text='Indica si la compra es visible para el cliente'),
        ),
    ]
