# Generated by Django 5.2.5 on 2025-11-09 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0020_auto_20251108_2013'),
        ('ventas', '0013_compra_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExtraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_extra', to='ventas.detallecompra')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termas.servicioterma')),
            ],
            options={
                'unique_together': {('detalle_compra', 'servicio')},
            },
        ),
    ]
