# Generated by Django 5.2.5 on 2025-11-09 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0020_auto_20251108_2013'),
        ('ventas', '0014_servicioextradetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_comision_plataforma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_para_terma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('pagado_terma', 'Pagado a Terma'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago_terma', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('referencia_pago_terma', models.CharField(blank=True, help_text='Referencia del pago enviado a la terma', max_length=100, null=True)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion_pago', to='ventas.compra')),
                ('plan_utilizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='termas.plansuscripcion')),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termas.terma')),
            ],
            options={
                'verbose_name': 'Distribución de Pago',
                'verbose_name_plural': 'Distribuciones de Pago',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPagoTerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago_usado', models.CharField(help_text='Método usado para pagar a la terma', max_length=100)),
                ('referencia_externa', models.CharField(blank=True, help_text='Referencia del sistema de pago externo', max_length=200, null=True)),
                ('info_pago_terma', models.JSONField(blank=True, help_text='Información de pago de la terma al momento del envío', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='ventas.distribucionpago')),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termas.terma')),
            ],
            options={
                'verbose_name': 'Historial de Pago a Terma',
                'verbose_name_plural': 'Historial de Pagos a Termas',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='ResumenComisionesPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado_termas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_transacciones', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen de Comisiones',
                'verbose_name_plural': 'Resúmenes de Comisiones',
                'ordering': ['-año', '-mes'],
                'unique_together': {('mes', 'año')},
            },
        ),
    ]
