# Generated by Django 5.2.5 on 2025-11-12 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_alter_horariodisponible_unique_together_and_more'),
        ('ventas', '0015_distribucionpago_historialpagoterma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='horario_disponible',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='horario_disponible',
        ),
        migrations.AddField(
            model_name='carrito',
            name='entrada_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.entradatipo'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='entrada_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.entradatipo'),
        ),
    ]
