# Generated by Django 5.2.5 on 2025-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_remove_carrito_horario_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroescaneo',
            name='email_finalizacion_enviado',
            field=models.BooleanField(default=False, help_text='Indica si se envió el email cuando la entrada se finalizó'),
        ),
        migrations.AddField(
            model_name='registroescaneo',
            name='fecha_email_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se envió el email de finalización', null=True),
        ),
    ]
