# Generated by Django 5.2.6 on 2025-09-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('termas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='terma',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termas_administradas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='terma',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad'),
        ),
        migrations.AddField(
            model_name='servicioterma',
            name='terma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='termas.terma'),
        ),
        migrations.AddField(
            model_name='imagenterma',
            name='terma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='termas.terma'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='terma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termas.terma'),
        ),
    ]
