# Generated by Django 5.2.5 on 2025-10-02 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0003_ciudad_region_alter_terma_ciudad_ciudad_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terma',
            name='ciudad',
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='termas.region')),
            ],
        ),
        migrations.AddField(
            model_name='terma',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='termas.comuna'),
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
