# Generated by Django 5.2.5 on 2025-10-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0005_cargar_regiones_comunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudterma',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='observaciones_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='terma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='termas.terma'),
        ),
    ]
