# Generated by Django 5.2.5 on 2025-10-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0006_solicitudterma_correo_institucional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudterma',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='termas.comuna'),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='termas.region'),
        ),
    ]
