# Generated by Django 5.2.5 on 2025-10-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0007_solicitudterma_comuna_solicitudterma_direccion_and_more'),
        ('usuarios', '0002_crear_roles_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudterma',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
