# Generated by Django 5.2.5 on 2025-10-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0008_alter_solicitudterma_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='terma',
            name='rut_empresa',
            field=models.CharField(blank=True, help_text='RUT de la empresa (ej: 12.345.678-9)', max_length=12, null=True),
        ),
    ]
