# Generated by Django 5.2.5 on 2025-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0010_solicitudterma_rut_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioterma',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicioterma',
            name='precio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
