# Generated by Django 5.2.5 on 2025-11-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0011_servicioterma_descripcion_servicioterma_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='terma',
            name='limite_ventas_diario',
            field=models.IntegerField(default=100, help_text='Límite máximo de ventas por día'),
        ),
    ]
