# Generated by Django 5.2.5 on 2025-11-05 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0012_terma_limite_ventas_diario'),
        ('usuarios', '0003_tokenrestablecercontrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('basico', 'Básico'), ('estandar', 'Estándar'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión (ej: 5.00 para 5%)', max_digits=5)),
                ('precio_mensual', models.DecimalField(decimal_places=2, help_text='Precio mensual del plan', max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, help_text='Precio anual del plan (con descuento)', max_digits=10)),
                ('limite_fotos', models.IntegerField(help_text='Límite de fotos que puede subir (-1 para ilimitado)')),
                ('posicion_preferencial', models.BooleanField(default=False, help_text='Si aparece en posiciones preferenciales')),
                ('marketing_premium', models.BooleanField(default=False, help_text='Si tiene acceso a marketing premium')),
                ('dashboard_avanzado', models.BooleanField(default=False, help_text='Si tiene acceso a dashboard avanzado')),
                ('soporte_prioritario', models.BooleanField(default=False, help_text='Si tiene soporte prioritario')),
                ('aparece_destacadas', models.BooleanField(default=False, help_text='Si aparece en sección de termas destacadas')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['porcentaje_comision'],
            },
        ),
        migrations.AddField(
            model_name='terma',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, help_text='Fecha del último pago de suscripción', null=True),
        ),
        migrations.AddField(
            model_name='terma',
            name='limite_fotos_actual',
            field=models.IntegerField(default=5, help_text='Límite actual de fotos basado en el plan (-1 para ilimitado)'),
        ),
        migrations.AddField(
            model_name='terma',
            name='porcentaje_comision_actual',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje de comisión actual basado en el plan', max_digits=5),
        ),
        migrations.CreateModel(
            name='ConfiguracionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_access_token', models.TextField(help_text='Access Token de Mercado Pago de la terma')),
                ('mercado_pago_user_id', models.CharField(help_text='User ID de Mercado Pago de la terma', max_length=100)),
                ('porcentaje_comision_actual', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión actual basado en su plan', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_configuracion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('terma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_split', to='termas.terma')),
            ],
            options={
                'verbose_name': 'Configuración Split Payment',
                'verbose_name_plural': 'Configuraciones Split Payment',
            },
        ),
        migrations.CreateModel(
            name='HistorialSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_suscripciones', to='termas.terma')),
                ('usuario_admin', models.ForeignKey(help_text='Admin que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('plan_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_como_anterior', to='termas.plansuscripcion')),
                ('plan_nuevo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_como_nuevo', to='termas.plansuscripcion')),
            ],
            options={
                'verbose_name': 'Historial de Suscripción',
                'verbose_name_plural': 'Historiales de Suscripciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddField(
            model_name='terma',
            name='plan_actual',
            field=models.ForeignKey(blank=True, help_text='Plan de suscripción actual', null=True, on_delete=django.db.models.deletion.SET_NULL, to='termas.plansuscripcion'),
        ),
        migrations.CreateModel(
            name='SuscripcionTerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_periodo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('pendiente_pago', 'Pendiente de Pago')], default='activa', max_length=20)),
                ('auto_renovacion', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='termas.plansuscripcion')),
                ('terma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_activa', to='termas.terma')),
            ],
            options={
                'verbose_name': 'Suscripción de Terma',
                'verbose_name_plural': 'Suscripciones de Termas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('mercado_pago_preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mercado_pago_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='termas.suscripcionterma')),
            ],
            options={
                'verbose_name': 'Pago de Suscripción',
                'verbose_name_plural': 'Pagos de Suscripciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
