# Generated by Django 5.2.5 on 2025-11-05 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0013_plansuscripcion_terma_fecha_ultimo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudterma',
            name='plan_seleccionado',
            field=models.ForeignKey(blank=True, help_text='Plan de suscripción seleccionado por la terma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='termas.plansuscripcion'),
        ),
    ]
