# Generated by Django 5.2.5 on 2025-11-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0014_solicitudterma_plan_seleccionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansuscripcion',
            name='precio_anual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio anual del plan (0 si solo se cobra comisión)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio mensual del plan (0 si solo se cobra comisión)', max_digits=10),
        ),
    ]
