# Generated by Django 5.2.5 on 2025-11-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0015_alter_plansuscripcion_precio_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terma',
            name='fecha_vinculacion_mp',
            field=models.DateTimeField(blank=True, help_text='Fecha de vinculación con Mercado Pago', null=True),
        ),
        migrations.AddField(
            model_name='terma',
            name='mercadopago_access_token',
            field=models.TextField(blank=True, help_text='Access token de Mercado Pago (encriptado)', null=True),
        ),
        migrations.AddField(
            model_name='terma',
            name='mercadopago_cuenta_vinculada',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta de Mercado Pago está vinculada'),
        ),
        migrations.AddField(
            model_name='terma',
            name='mercadopago_user_id',
            field=models.CharField(blank=True, help_text='ID de usuario de Mercado Pago para Split Payments', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='terma',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo disponible en la billetera de la terma', max_digits=12),
        ),
        migrations.AddField(
            model_name='terma',
            name='total_ingresos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total de ingresos históricos', max_digits=12),
        ),
    ]
