# Generated by Django 5.2.5 on 2025-11-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0016_terma_fecha_vinculacion_mp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terma',
            name='fecha_vinculacion_mp',
        ),
        migrations.RemoveField(
            model_name='terma',
            name='mercadopago_access_token',
        ),
        migrations.RemoveField(
            model_name='terma',
            name='mercadopago_cuenta_vinculada',
        ),
        migrations.RemoveField(
            model_name='terma',
            name='mercadopago_user_id',
        ),
        migrations.RemoveField(
            model_name='terma',
            name='saldo_disponible',
        ),
        migrations.RemoveField(
            model_name='terma',
            name='total_ingresos',
        ),
        migrations.DeleteModel(
            name='ConfiguracionSplit',
        ),
    ]
