# Generated by Django 5.2.5 on 2025-11-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0017_remove_split_payment_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcionterma',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='suscripcionterma',
            name='terma',
        ),
        migrations.RemoveField(
            model_name='plansuscripcion',
            name='precio_anual',
        ),
        migrations.RemoveField(
            model_name='plansuscripcion',
            name='precio_mensual',
        ),
        migrations.RemoveField(
            model_name='terma',
            name='fecha_ultimo_pago',
        ),
        migrations.DeleteModel(
            name='PagoSuscripcion',
        ),
        migrations.DeleteModel(
            name='SuscripcionTerma',
        ),
    ]
