# Generated by Django 5.2.5 on 2025-11-08 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0018_remove_suscripcionterma_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('usuario', 'terma')},
        ),
    ]
