# Generated by Django 5.2.5 on 2025-11-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0019_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
    ]
