# Generated by Django 5.2.5 on 2025-11-21 01:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0020_auto_20251108_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenterma',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='servicioterma',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='solicitudterma',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='terma',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
