# Generated by Django 5.2.5 on 2025-10-04 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_crear_roles_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRestablecerContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Token para restablecer contraseña',
                'verbose_name_plural': 'Tokens para restablecer contraseña',
            },
        ),
    ]
