# Generated by Django 5.2.5 on 2025-11-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_upgrade_auth_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenrestablecercontrasena',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
