# Generated by Django 5.2.5 on 2025-11-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_fix_token_duplicates'),
        ('usuarios', '0006_make_token_unique'),
    ]

    operations = [
    ]
