# Generated by Django 5.2.5 on 2025-11-08 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0019_alter_calificacion_options_and_more'),
        ('usuarios', '0007_merge_20251108_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenrestablecercontrasena',
            name='ip_creacion',
        ),
        migrations.RemoveField(
            model_name='tokenrestablecercontrasena',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='tokenrestablecercontrasena',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='termas.terma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'terma')},
            },
        ),
    ]
