# Generated by Django 5.2.5 on 2025-11-08 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0019_alter_calificacion_options_and_more'),
        ('usuarios', '0008_remove_tokenrestablecercontrasena_ip_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='termas.terma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'terma'), name='unique_usuario_terma_favorito'),
        ),
    ]
