# Generated by Django 5.2.5 on 2025-11-08 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0019_alter_calificacion_options_and_more'),
        ('usuarios', '0009_auto_20251108_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='termas.terma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'terma')},
        ),
    ]
