# Generated by Django 5.2.5 on 2025-11-11 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termas', '0020_auto_20251108_2013'),
        ('usuarios', '0010_add_favorito_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha en que comenzó a trabajar en la terma')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha en que dejó de trabajar (null = aún activo)', null=True)),
                ('motivo_fin', models.CharField(blank=True, choices=[('desactivado', 'Cuenta desactivada'), ('cambio_rol', 'Cambio de rol'), ('transferido', 'Transferido a otra terma'), ('renuncia', 'Renuncia voluntaria')], help_text='Motivo por el cual dejó de trabajar', max_length=20, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este es el registro actual activo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_trabajadores', to='termas.terma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_trabajador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Trabajador',
                'verbose_name_plural': 'Historiales de Trabajadores',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['usuario', 'terma'], name='usuarios_hi_usuario_80e02f_idx'), models.Index(fields=['terma', 'activo'], name='usuarios_hi_terma_i_4f308c_idx'), models.Index(fields=['usuario', 'activo'], name='usuarios_hi_usuario_8506ab_idx')],
            },
        ),
    ]
