# Generated by Django 5.2.5 on 2025-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_historial_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiene_password_temporal',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene una contraseña temporal que debe cambiar'),
        ),
    ]
