# Generated by Django 5.2.5 on 2025-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_tiene_password_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_invitado',
            field=models.BooleanField(default=False, help_text='Indica si es un usuario creado para compra como invitado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ultima_actividad',
            field=models.DateTimeField(blank=True, help_text='Última actividad del usuario invitado', null=True),
        ),
    ]
