# Generated by Django 5.2.5 on 2025-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuario_es_invitado_usuario_fecha_ultima_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_ultima_actividad',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_invitado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario fue creado como invitado (solo con email) para una compra'),
        ),
    ]
