# Generated by Django 5.2.5 on 2025-11-21 01:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_usuario_fecha_ultima_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
