# Generated by Django 5.2.5 on 2025-09-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('termas', '0003_ciudad_region_alter_terma_ciudad_ciudad_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_horas', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termas.terma')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupos_totales', models.IntegerField()),
                ('cupos_disponibles', models.IntegerField()),
                ('entrada_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.entradatipo')),
                ('terma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termas.terma')),
            ],
        ),
    ]
