# Generated by Django 5.2.5 on 2025-10-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
        ('termas', '0011_servicioterma_descripcion_servicioterma_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradatipo',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='entradas', to='termas.servicioterma'),
        ),
    ]
