# Generated by Django 5.2.5 on 2025-11-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_entradatipo_duracion_tipo'),
        ('termas', '0018_remove_suscripcionterma_plan_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariodisponible',
            unique_together={('terma', 'entrada_tipo', 'fecha')},
        ),
    ]
