# Generated by Django 5.2.5 on 2025-11-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_alter_horariodisponible_unique_together'),
        ('termas', '0020_auto_20251108_2013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariodisponible',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='horariodisponible',
            name='entrada_tipo',
        ),
        migrations.RemoveField(
            model_name='horariodisponible',
            name='terma',
        ),
        migrations.AddField(
            model_name='entradatipo',
            name='cupos_disponibles',
            field=models.IntegerField(blank=True, help_text='Cupos restantes para esta fecha', null=True),
        ),
        migrations.AddField(
            model_name='entradatipo',
            name='cupos_totales',
            field=models.IntegerField(blank=True, help_text='Total de cupos disponibles para esta fecha', null=True),
        ),
        migrations.AddField(
            model_name='entradatipo',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha para la cual esta entrada está disponible', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='entradatipo',
            unique_together={('terma', 'nombre', 'fecha')},
        ),
    ]
