# Generated by Django 5.2.5 on 2025-11-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_alter_horariodisponible_unique_together_and_more'),
        ('ventas', '0016_remove_carrito_horario_disponible_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorarioDisponible',
        ),
    ]
