# Generated by Django 5.2.5 on 2025-11-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0006_delete_horariodisponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradatipo',
            name='duracion_tipo',
            field=models.CharField(choices=[('dia', 'Por el día'), ('medio_dia', 'Medio día'), ('noche', 'Por la noche'), ('dia_completo', 'Día completo')], default='dia', help_text='Define si la entrada es para uso diurno, nocturno o día completo', max_length=20),
        ),
    ]
