# Generated by Django 5.2.5 on 2025-11-21 01:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0007_alter_entradatipo_duracion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradatipo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
